import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "app/lib/chatScroll.test.ts",
      "app/lib/notificationNavigator.test.ts",
      "app/lib/aiSafety.test.ts",
      "app/lib/securityHeaders.test.ts",
      "lib/supportReport.test.ts",
      "lib/sanitize.test.ts",
      "lib/imageValidator.test.ts",
      "app/api/payments/paymentSecurity.test.ts",
      "lib/authSession.test.ts",
      "lib/idorSecurity.test.ts",
      "app/lib/authSecurityIntegration.test.ts",
      "app/api/auth/refresh.security.test.ts",
      "app/api/auth/logout.security.test.ts",
      "app/api/authFlowSecurity.test.ts",
      "app/api/chat/message/edit/route.test.ts",
      "app/api/chat/chatRouteSecurity.test.ts",
      "lib/requestMetadata.test.ts",
      "lib/internalJobAuth.test.ts",
      "lib/realtimeRedis.test.ts",
      "lib/aiBillingSecurity.test.ts",
      "lib/aiSecurityDecision.test.ts",
      "lib/aiGenerationLock.test.ts",
      "lib/initialChatIdempotency.test.ts",
      "lib/requestBody.test.ts",
      "lib/chatPolicy.test.ts",
      "lib/rateLimitSafety.test.ts",
      "lib/providerUsageAccounting.test.ts",
      "lib/normalChatCancellation.test.ts",
      "lib/streamingTurnPersistence.test.ts",
      "lib/nonStreamingChatPersistence.test.ts",
      "lib/conversationSummary.test.ts",
      "lib/normalChatHistory.test.ts",
      "lib/promptInjectionDetector.test.ts",
      "lib/regenerationHistory.test.ts",
      "services/liveTutorGeminiLiveService.test.ts",
      "services/geminiService.test.ts",
      "services/geminiPricing.test.ts",
      "services/geminiDailyBudget.test.ts",
      "services/geminiAttemptAccounting.test.ts",
      "services/contextBudgetManager.test.ts",
      "services/chatService.test.ts",
      "services/chatOperationService.test.ts",
      "services/productPolicy.test.ts",
      "services/entitlementFoundation.test.ts",
      "services/liveTutorAudioProtocol.test.ts",
      "services/liveTutorVoiceFoundation.test.ts",
      "services/liveTutorVoiceGateway.test.ts",
      "services/liveTutorVoiceProfiles.test.ts",
      "services/dataRetentionService.test.ts",
      "lib/legalConsent.test.ts",
      "lib/liveTutorLimits.test.ts",
      "services/liveTutorBillingPolicy.test.ts",
      "services/accountDeletionPolicy.test.ts",
      "services/accountDeletionService.test.ts",
      "services/nativeStoreService.googlePlay.test.ts",
      "services/transactionalEmailService.test.ts",
      "services/userAccountService.oauth.test.ts",
      "services/supabaseOAuthService.test.ts",
      "app/api/payments/mobile/google-rtdn/route.test.ts",
    ],
    exclude: [
      "node_modules/**",
      "scripts/**",
    ],
    env: {
      AUTH_WEB_BASE_URL: "https://auth.test.invalid",
    },
  },
});
