import { NextResponse } from 'next/server';
import { getUserFromRequest } from '@/app/lib/auth';
import logger from '@/lib/logger';
import { getNotifications, clearNotifications } from '@/app/services/notificationService';

function parsePositiveInt(value: string | null, fallback: number) {
  const parsed = Number(value ?? '');
  return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : fallback;
}

export async function GET(req: Request) {
  try {
    const user = await getUserFromRequest(req);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const url = new URL(req.url);
    const page = parsePositiveInt(url.searchParams.get('page'), 1);
    const pageSize = parsePositiveInt(url.searchParams.get('pageSize'), 20);

    const result = await getNotifications(user.id, page, pageSize);
    return NextResponse.json(result);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal Server Error';
    logger.error('Failed to fetch notifications', { error: message });
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function POST(req: Request) {
  // Notifications are generated by trusted server-side product flows. Allowing
  // a signed-in client to manufacture them creates spoofing and cross-account
  // idempotency risks, so the public collection endpoint is deliberately read-only.
  void req;
  return NextResponse.json(
    { error: 'Notification creation is not available from the client.' },
    { status: 405, headers: { Allow: 'GET, DELETE' } },
  );
}

export async function DELETE(req: Request) {
  try {
    const user = await getUserFromRequest(req);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const deletedCount = await clearNotifications(user.id);
    return NextResponse.json({ success: true, deletedCount });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal Server Error';
    logger.error('Failed to clear notifications', { error: message });
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
